services:
  web:
    build:
      args:
        TORCH_INDEX_URL: https://download.pytorch.org/whl/cu124
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
